#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_DQUOTE = 1,
  aux_sym__string_token1 = 2,
  anon_sym_COLON = 3,
  anon_sym_QMARK = 4,
  anon_sym_BANG = 5,
  anon_sym_STAR = 6,
  anon_sym_PLUS = 7,
  sym_identifier = 8,
  anon_sym_AT = 9,
  anon_sym_SEMI = 10,
  aux_sym_comment_token1 = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  sym_program = 16,
  sym__definition = 17,
  sym__string = 18,
  sym__field_name = 19,
  sym_predicate_type = 20,
  sym_quantifier = 21,
  sym_field_definition = 22,
  sym_capture = 23,
  sym_string = 24,
  sym_parameters = 25,
  sym_comment = 26,
  sym_list = 27,
  sym_grouping = 28,
  sym_anonymous_node = 29,
  sym_named_node = 30,
  sym_predicate = 31,
  aux_sym_program_repeat1 = 32,
  aux_sym__string_repeat1 = 33,
  aux_sym_parameters_repeat1 = 34,
  aux_sym_list_repeat1 = 35,
  aux_sym_named_node_repeat1 = 36,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_token1] = "_string_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK] = "?",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [sym_identifier] = "identifier",
  [anon_sym_AT] = "@",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_program] = "program",
  [sym__definition] = "_definition",
  [sym__string] = "_string",
  [sym__field_name] = "_field_name",
  [sym_predicate_type] = "predicate_type",
  [sym_quantifier] = "quantifier",
  [sym_field_definition] = "field_definition",
  [sym_capture] = "capture",
  [sym_string] = "string",
  [sym_parameters] = "parameters",
  [sym_comment] = "comment",
  [sym_list] = "list",
  [sym_grouping] = "grouping",
  [sym_anonymous_node] = "anonymous_node",
  [sym_named_node] = "named_node",
  [sym_predicate] = "predicate",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym__string_repeat1] = "_string_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_named_node_repeat1] = "named_node_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_token1] = aux_sym__string_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_identifier] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_program] = sym_program,
  [sym__definition] = sym__definition,
  [sym__string] = sym__string,
  [sym__field_name] = sym__field_name,
  [sym_predicate_type] = sym_predicate_type,
  [sym_quantifier] = sym_quantifier,
  [sym_field_definition] = sym_field_definition,
  [sym_capture] = sym_capture,
  [sym_string] = sym_string,
  [sym_parameters] = sym_parameters,
  [sym_comment] = sym_comment,
  [sym_list] = sym_list,
  [sym_grouping] = sym_grouping,
  [sym_anonymous_node] = sym_anonymous_node,
  [sym_named_node] = sym_named_node,
  [sym_predicate] = sym_predicate,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym__string_repeat1] = aux_sym__string_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_named_node_repeat1] = aux_sym_named_node_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym__field_name] = {
    .visible = false,
    .named = true,
  },
  [sym_predicate_type] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_capture] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_grouping] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_node] = {
    .visible = true,
    .named = true,
  },
  [sym_named_node] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_named_node_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_name = 1,
  field_parameters = 2,
  field_quantifier = 3,
  field_type = 4,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_quantifier] = "quantifier",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[9] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 3},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_quantifier, 1},
  [1] =
    {field_quantifier, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_quantifier, 3},
  [4] =
    {field_name, 1},
    {field_quantifier, 3},
  [6] =
    {field_name, 0},
  [7] =
    {field_name, 1},
    {field_parameters, 3},
    {field_type, 2},
  [10] =
    {field_name, 1},
    {field_quantifier, 4},
};

static TSSymbol ts_alias_sequences[9][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '+') ADVANCE(9);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym__string_token1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(58),
    [sym__definition] = STATE(15),
    [sym__string] = STATE(8),
    [sym_comment] = STATE(15),
    [sym_list] = STATE(15),
    [sym_grouping] = STATE(15),
    [sym_anonymous_node] = STATE(15),
    [sym_named_node] = STATE(15),
    [sym_predicate] = STATE(15),
    [aux_sym_program_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
  },
  [2] = {
    [sym__definition] = STATE(4),
    [sym__string] = STATE(8),
    [sym__field_name] = STATE(18),
    [sym_predicate_type] = STATE(47),
    [sym_field_definition] = STATE(4),
    [sym_comment] = STATE(4),
    [sym_list] = STATE(4),
    [sym_grouping] = STATE(4),
    [sym_anonymous_node] = STATE(4),
    [sym_named_node] = STATE(4),
    [sym_predicate] = STATE(4),
    [aux_sym_named_node_repeat1] = STATE(4),
    [anon_sym_DQUOTE] = ACTIONS(5),
    [anon_sym_QMARK] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(17),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(22), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym__string,
    STATE(18), 1,
      sym__field_name,
    STATE(3), 9,
      sym__definition,
      sym_field_definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_named_node_repeat1,
  [36] = 9,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(36), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym__string,
    STATE(18), 1,
      sym__field_name,
    STATE(3), 9,
      sym__definition,
      sym_field_definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_named_node_repeat1,
  [72] = 7,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      anon_sym_SEMI,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym__string,
    ACTIONS(38), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [103] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(40), 1,
      sym_quantifier,
    STATE(42), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [129] = 8,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym__string,
    STATE(17), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [161] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(35), 1,
      sym_quantifier,
    STATE(23), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(62), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [187] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(29), 1,
      sym_quantifier,
    STATE(28), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [213] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(22), 1,
      sym_quantifier,
    STATE(32), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [239] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(25), 1,
      sym_quantifier,
    STATE(26), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [265] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(33), 1,
      sym_quantifier,
    STATE(34), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [291] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(41), 1,
      sym_quantifier,
    STATE(39), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(72), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [317] = 7,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      sym__string,
    STATE(16), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [346] = 7,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym__string,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [375] = 7,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      sym__string,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [404] = 7,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym__string,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [433] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym__string,
    STATE(50), 7,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
  [458] = 1,
    ACTIONS(82), 12,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      sym_identifier,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [473] = 1,
    ACTIONS(84), 12,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      sym_identifier,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [488] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(86), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [506] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(27), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(88), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [524] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(90), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [542] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [560] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(94), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [578] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [596] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(96), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [614] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(98), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [632] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(24), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [650] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(102), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [668] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(104), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [686] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(106), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [704] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(36), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(108), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [722] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [740] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(37), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(110), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [758] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(112), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [776] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(114), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [794] = 3,
    ACTIONS(118), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(116), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [812] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [830] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(31), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [848] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(30), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [866] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [884] = 1,
    ACTIONS(127), 9,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [896] = 1,
    ACTIONS(129), 9,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [908] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_AT,
    ACTIONS(131), 1,
      sym_identifier,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym__string,
    STATE(49), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [929] = 1,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [940] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_AT,
    ACTIONS(137), 1,
      sym_identifier,
    STATE(51), 1,
      sym__string,
    STATE(59), 1,
      sym_parameters,
    STATE(45), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [961] = 1,
    ACTIONS(139), 8,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [972] = 6,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(144), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_AT,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym__string,
    STATE(49), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [993] = 1,
    ACTIONS(152), 6,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1002] = 1,
    ACTIONS(154), 4,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1009] = 1,
    ACTIONS(156), 4,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1016] = 3,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    ACTIONS(160), 1,
      aux_sym__string_token1,
    STATE(56), 1,
      aux_sym__string_repeat1,
  [1026] = 3,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    ACTIONS(164), 1,
      aux_sym__string_token1,
    STATE(53), 1,
      aux_sym__string_repeat1,
  [1036] = 1,
    ACTIONS(166), 3,
      anon_sym_DQUOTE,
      sym_identifier,
      anon_sym_AT,
  [1042] = 3,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      aux_sym__string_token1,
    STATE(56), 1,
      aux_sym__string_repeat1,
  [1052] = 1,
    ACTIONS(173), 1,
      anon_sym_COLON,
  [1056] = 1,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
  [1060] = 1,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
  [1064] = 1,
    ACTIONS(179), 1,
      aux_sym_comment_token1,
  [1068] = 1,
    ACTIONS(181), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 103,
  [SMALL_STATE(7)] = 129,
  [SMALL_STATE(8)] = 161,
  [SMALL_STATE(9)] = 187,
  [SMALL_STATE(10)] = 213,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 265,
  [SMALL_STATE(13)] = 291,
  [SMALL_STATE(14)] = 317,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 375,
  [SMALL_STATE(17)] = 404,
  [SMALL_STATE(18)] = 433,
  [SMALL_STATE(19)] = 458,
  [SMALL_STATE(20)] = 473,
  [SMALL_STATE(21)] = 488,
  [SMALL_STATE(22)] = 506,
  [SMALL_STATE(23)] = 524,
  [SMALL_STATE(24)] = 542,
  [SMALL_STATE(25)] = 560,
  [SMALL_STATE(26)] = 578,
  [SMALL_STATE(27)] = 596,
  [SMALL_STATE(28)] = 614,
  [SMALL_STATE(29)] = 632,
  [SMALL_STATE(30)] = 650,
  [SMALL_STATE(31)] = 668,
  [SMALL_STATE(32)] = 686,
  [SMALL_STATE(33)] = 704,
  [SMALL_STATE(34)] = 722,
  [SMALL_STATE(35)] = 740,
  [SMALL_STATE(36)] = 758,
  [SMALL_STATE(37)] = 776,
  [SMALL_STATE(38)] = 794,
  [SMALL_STATE(39)] = 812,
  [SMALL_STATE(40)] = 830,
  [SMALL_STATE(41)] = 848,
  [SMALL_STATE(42)] = 866,
  [SMALL_STATE(43)] = 884,
  [SMALL_STATE(44)] = 896,
  [SMALL_STATE(45)] = 908,
  [SMALL_STATE(46)] = 929,
  [SMALL_STATE(47)] = 940,
  [SMALL_STATE(48)] = 961,
  [SMALL_STATE(49)] = 972,
  [SMALL_STATE(50)] = 993,
  [SMALL_STATE(51)] = 1002,
  [SMALL_STATE(52)] = 1009,
  [SMALL_STATE(53)] = 1016,
  [SMALL_STATE(54)] = 1026,
  [SMALL_STATE(55)] = 1036,
  [SMALL_STATE(56)] = 1042,
  [SMALL_STATE(57)] = 1052,
  [SMALL_STATE(58)] = 1056,
  [SMALL_STATE(59)] = 1060,
  [SMALL_STATE(60)] = 1064,
  [SMALL_STATE(61)] = 1068,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(54),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(57),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(60),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(14),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(54),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(60),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(14),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(7),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 4, .production_id = 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 3, .production_id = 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4, .production_id = 4),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 6, .production_id = 8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 5, .production_id = 4),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 5),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, .production_id = 4),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3, .production_id = 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 2, .production_id = 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4, .production_id = 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 3, .production_id = 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(61),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 4, .production_id = 5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 2, .production_id = 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantifier, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 5, .production_id = 7),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(54),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(49),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(61),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 2, .production_id = 6),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_name, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_type, 1),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_repeat1, 2), SHIFT_REPEAT(56),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [175] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_query(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
