#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_COLON = 1,
  anon_sym_QMARK = 2,
  anon_sym_BANG = 3,
  anon_sym_STAR = 4,
  anon_sym_PLUS = 5,
  sym_identifier = 6,
  anon_sym_AT = 7,
  aux_sym_string_token1 = 8,
  anon_sym_SEMI = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  sym_program = 15,
  sym__definition = 16,
  sym__field_name = 17,
  sym_predicate_type = 18,
  sym_quantifier = 19,
  sym_field_definition = 20,
  sym_capture = 21,
  sym_string = 22,
  sym_parameters = 23,
  sym_comment = 24,
  sym_list = 25,
  sym_grouping = 26,
  sym_anonymous_node = 27,
  sym_named_node = 28,
  sym_predicate = 29,
  aux_sym_program_repeat1 = 30,
  aux_sym_parameters_repeat1 = 31,
  aux_sym_list_repeat1 = 32,
  aux_sym_named_node_repeat1 = 33,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK] = "?",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [sym_identifier] = "identifier",
  [anon_sym_AT] = "@",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_program] = "program",
  [sym__definition] = "_definition",
  [sym__field_name] = "_field_name",
  [sym_predicate_type] = "predicate_type",
  [sym_quantifier] = "quantifier",
  [sym_field_definition] = "field_definition",
  [sym_capture] = "capture",
  [sym_string] = "string",
  [sym_parameters] = "parameters",
  [sym_comment] = "comment",
  [sym_list] = "list",
  [sym_grouping] = "grouping",
  [sym_anonymous_node] = "anonymous_node",
  [sym_named_node] = "named_node",
  [sym_predicate] = "predicate",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_named_node_repeat1] = "named_node_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_identifier] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_program] = sym_program,
  [sym__definition] = sym__definition,
  [sym__field_name] = sym__field_name,
  [sym_predicate_type] = sym_predicate_type,
  [sym_quantifier] = sym_quantifier,
  [sym_field_definition] = sym_field_definition,
  [sym_capture] = sym_capture,
  [sym_string] = sym_string,
  [sym_parameters] = sym_parameters,
  [sym_comment] = sym_comment,
  [sym_list] = sym_list,
  [sym_grouping] = sym_grouping,
  [sym_anonymous_node] = sym_anonymous_node,
  [sym_named_node] = sym_named_node,
  [sym_predicate] = sym_predicate,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_named_node_repeat1] = aux_sym_named_node_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__field_name] = {
    .visible = false,
    .named = true,
  },
  [sym_predicate_type] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_capture] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_grouping] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_node] = {
    .visible = true,
    .named = true,
  },
  [sym_named_node] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_named_node_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_name = 1,
  field_parameters = 2,
  field_quantifier = 3,
  field_type = 4,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_quantifier] = "quantifier",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[9] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 3},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_quantifier, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_quantifier, 2},
  [3] =
    {field_quantifier, 3},
  [4] =
    {field_name, 1},
    {field_quantifier, 3},
  [6] =
    {field_name, 0},
  [7] =
    {field_name, 1},
    {field_parameters, 3},
    {field_type, 2},
  [10] =
    {field_name, 1},
    {field_quantifier, 4},
};

static TSSymbol ts_alias_sequences[9][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '?') ADVANCE(4);
      if (lookahead == '@') ADVANCE(9);
      if (lookahead == '[') ADVANCE(14);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 12},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(53),
    [sym__definition] = STATE(15),
    [sym_comment] = STATE(15),
    [sym_list] = STATE(15),
    [sym_grouping] = STATE(15),
    [sym_anonymous_node] = STATE(15),
    [sym_named_node] = STATE(15),
    [sym_predicate] = STATE(15),
    [aux_sym_program_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_string_token1] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
  },
  [2] = {
    [sym__definition] = STATE(4),
    [sym__field_name] = STATE(18),
    [sym_predicate_type] = STATE(47),
    [sym_field_definition] = STATE(4),
    [sym_comment] = STATE(4),
    [sym_list] = STATE(4),
    [sym_grouping] = STATE(4),
    [sym_anonymous_node] = STATE(4),
    [sym_named_node] = STATE(4),
    [sym_predicate] = STATE(4),
    [aux_sym_named_node_repeat1] = STATE(4),
    [anon_sym_QMARK] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [aux_sym_string_token1] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(17),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(22), 1,
      aux_sym_string_token1,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym__field_name,
    STATE(3), 9,
      sym__definition,
      sym_field_definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_named_node_repeat1,
  [33] = 8,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(36), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym__field_name,
    STATE(3), 9,
      sym__definition,
      sym_field_definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_named_node_repeat1,
  [66] = 6,
    ACTIONS(40), 1,
      aux_sym_string_token1,
    ACTIONS(43), 1,
      anon_sym_SEMI,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [94] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(30), 1,
      sym_quantifier,
    STATE(28), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [120] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(27), 1,
      sym_quantifier,
    STATE(26), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [146] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(40), 1,
      sym_quantifier,
    STATE(37), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [172] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym_quantifier,
    STATE(39), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(62), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [198] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(35), 1,
      sym_quantifier,
    STATE(36), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [224] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(22), 1,
      sym_quantifier,
    STATE(23), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [250] = 5,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(31), 1,
      sym_quantifier,
    STATE(32), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(54), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [276] = 7,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(17), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [305] = 6,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    STATE(16), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [331] = 6,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [357] = 6,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [383] = 6,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(5), 8,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [409] = 5,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(46), 7,
      sym__definition,
      sym_comment,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
  [431] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [449] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [467] = 3,
    ACTIONS(88), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(86), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [485] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(34), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(91), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [503] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [521] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(93), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [539] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(95), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [557] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(97), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [575] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(24), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [593] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(101), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [611] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [629] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(20), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(105), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [647] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(19), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [665] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [683] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [701] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [719] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(33), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [737] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [755] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [773] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [791] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [809] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(25), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [827] = 1,
    ACTIONS(123), 9,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_AT,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [839] = 1,
    ACTIONS(125), 9,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_AT,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [851] = 1,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [862] = 1,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [873] = 4,
    ACTIONS(56), 1,
      anon_sym_AT,
    ACTIONS(131), 1,
      aux_sym_string_token1,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(48), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [888] = 1,
    ACTIONS(135), 6,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [897] = 4,
    ACTIONS(56), 1,
      anon_sym_AT,
    ACTIONS(131), 1,
      aux_sym_string_token1,
    STATE(52), 1,
      sym_parameters,
    STATE(45), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [912] = 4,
    ACTIONS(137), 1,
      anon_sym_AT,
    ACTIONS(140), 1,
      aux_sym_string_token1,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(48), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [927] = 1,
    ACTIONS(145), 4,
      aux_sym_string_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [934] = 1,
    ACTIONS(147), 3,
      anon_sym_AT,
      aux_sym_string_token1,
      anon_sym_RPAREN,
  [940] = 1,
    ACTIONS(149), 2,
      anon_sym_AT,
      aux_sym_string_token1,
  [945] = 1,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
  [949] = 1,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
  [953] = 1,
    ACTIONS(155), 1,
      sym_identifier,
  [957] = 1,
    ACTIONS(157), 1,
      anon_sym_COLON,
  [961] = 1,
    ACTIONS(159), 1,
      aux_sym_comment_token1,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 33,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 172,
  [SMALL_STATE(10)] = 198,
  [SMALL_STATE(11)] = 224,
  [SMALL_STATE(12)] = 250,
  [SMALL_STATE(13)] = 276,
  [SMALL_STATE(14)] = 305,
  [SMALL_STATE(15)] = 331,
  [SMALL_STATE(16)] = 357,
  [SMALL_STATE(17)] = 383,
  [SMALL_STATE(18)] = 409,
  [SMALL_STATE(19)] = 431,
  [SMALL_STATE(20)] = 449,
  [SMALL_STATE(21)] = 467,
  [SMALL_STATE(22)] = 485,
  [SMALL_STATE(23)] = 503,
  [SMALL_STATE(24)] = 521,
  [SMALL_STATE(25)] = 539,
  [SMALL_STATE(26)] = 557,
  [SMALL_STATE(27)] = 575,
  [SMALL_STATE(28)] = 593,
  [SMALL_STATE(29)] = 611,
  [SMALL_STATE(30)] = 629,
  [SMALL_STATE(31)] = 647,
  [SMALL_STATE(32)] = 665,
  [SMALL_STATE(33)] = 683,
  [SMALL_STATE(34)] = 701,
  [SMALL_STATE(35)] = 719,
  [SMALL_STATE(36)] = 737,
  [SMALL_STATE(37)] = 755,
  [SMALL_STATE(38)] = 773,
  [SMALL_STATE(39)] = 791,
  [SMALL_STATE(40)] = 809,
  [SMALL_STATE(41)] = 827,
  [SMALL_STATE(42)] = 839,
  [SMALL_STATE(43)] = 851,
  [SMALL_STATE(44)] = 862,
  [SMALL_STATE(45)] = 873,
  [SMALL_STATE(46)] = 888,
  [SMALL_STATE(47)] = 897,
  [SMALL_STATE(48)] = 912,
  [SMALL_STATE(49)] = 927,
  [SMALL_STATE(50)] = 934,
  [SMALL_STATE(51)] = 940,
  [SMALL_STATE(52)] = 945,
  [SMALL_STATE(53)] = 949,
  [SMALL_STATE(54)] = 953,
  [SMALL_STATE(55)] = 957,
  [SMALL_STATE(56)] = 961,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(55),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(6),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(56),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(14),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(56),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(14),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 4, .production_id = 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 3, .production_id = 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 2),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4, .production_id = 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 3, .production_id = 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(54),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 6, .production_id = 8),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 5, .production_id = 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 8),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 5),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 2, .production_id = 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3, .production_id = 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, .production_id = 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 4, .production_id = 5),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4, .production_id = 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantifier, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 2, .production_id = 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 5, .production_id = 7),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 2, .production_id = 6),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(54),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(50),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_name, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_type, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [153] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_scheme(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
