#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_COLON = 1,
  anon_sym_QMARK = 2,
  anon_sym_BANG = 3,
  anon_sym_STAR = 4,
  anon_sym_PLUS = 5,
  sym_identifier = 6,
  sym_capture_identifier = 7,
  anon_sym_AT = 8,
  aux_sym_string_token1 = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  sym_program = 14,
  sym__definition = 15,
  sym__field_name = 16,
  sym_predicate_type = 17,
  sym_quantifier = 18,
  sym_field_definition = 19,
  sym_capture = 20,
  sym_string = 21,
  sym_parameters = 22,
  sym_list = 23,
  sym_grouping = 24,
  sym_anonymous_node = 25,
  sym_named_node = 26,
  sym_predicate = 27,
  aux_sym_program_repeat1 = 28,
  aux_sym_parameters_repeat1 = 29,
  aux_sym_list_repeat1 = 30,
  aux_sym_named_node_repeat1 = 31,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK] = "?",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [sym_identifier] = "identifier",
  [sym_capture_identifier] = "capture_identifier",
  [anon_sym_AT] = "@",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_program] = "program",
  [sym__definition] = "_definition",
  [sym__field_name] = "_field_name",
  [sym_predicate_type] = "predicate_type",
  [sym_quantifier] = "quantifier",
  [sym_field_definition] = "field_definition",
  [sym_capture] = "capture",
  [sym_string] = "string",
  [sym_parameters] = "parameters",
  [sym_list] = "list",
  [sym_grouping] = "grouping",
  [sym_anonymous_node] = "anonymous_node",
  [sym_named_node] = "named_node",
  [sym_predicate] = "predicate",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_named_node_repeat1] = "named_node_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_identifier] = sym_identifier,
  [sym_capture_identifier] = sym_capture_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_program] = sym_program,
  [sym__definition] = sym__definition,
  [sym__field_name] = sym__field_name,
  [sym_predicate_type] = sym_predicate_type,
  [sym_quantifier] = sym_quantifier,
  [sym_field_definition] = sym_field_definition,
  [sym_capture] = sym_capture,
  [sym_string] = sym_string,
  [sym_parameters] = sym_parameters,
  [sym_list] = sym_list,
  [sym_grouping] = sym_grouping,
  [sym_anonymous_node] = sym_anonymous_node,
  [sym_named_node] = sym_named_node,
  [sym_predicate] = sym_predicate,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_named_node_repeat1] = aux_sym_named_node_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_capture_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__field_name] = {
    .visible = false,
    .named = true,
  },
  [sym_predicate_type] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_capture] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_grouping] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_node] = {
    .visible = true,
    .named = true,
  },
  [sym_named_node] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_named_node_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_name = 1,
  field_parameters = 2,
  field_quantifier = 3,
  field_type = 4,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_quantifier] = "quantifier",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[9] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 3},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_quantifier, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_quantifier, 2},
  [3] =
    {field_quantifier, 3},
  [4] =
    {field_name, 1},
    {field_quantifier, 3},
  [6] =
    {field_name, 0},
  [7] =
    {field_name, 1},
    {field_parameters, 3},
    {field_type, 2},
  [10] =
    {field_name, 1},
    {field_quantifier, 4},
};

static TSSymbol ts_alias_sequences[9][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '+') ADVANCE(8);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '?') ADVANCE(5);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '$' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_capture_identifier);
      if (lookahead == '$' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(52),
    [sym__definition] = STATE(15),
    [sym_list] = STATE(15),
    [sym_grouping] = STATE(15),
    [sym_anonymous_node] = STATE(15),
    [sym_named_node] = STATE(15),
    [sym_predicate] = STATE(15),
    [aux_sym_program_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_string_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
  },
  [2] = {
    [sym__definition] = STATE(8),
    [sym__field_name] = STATE(40),
    [sym_predicate_type] = STATE(45),
    [sym_field_definition] = STATE(8),
    [sym_list] = STATE(8),
    [sym_grouping] = STATE(8),
    [sym_anonymous_node] = STATE(8),
    [sym_named_node] = STATE(8),
    [sym_predicate] = STATE(8),
    [aux_sym_named_node_repeat1] = STATE(8),
    [anon_sym_QMARK] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [aux_sym_string_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(33), 1,
      sym_quantifier,
    STATE(34), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(17), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [25] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(31), 1,
      sym_quantifier,
    STATE(28), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(23), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [50] = 7,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(28), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym__field_name,
    STATE(5), 8,
      sym__definition,
      sym_field_definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_named_node_repeat1,
  [79] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(26), 1,
      sym_quantifier,
    STATE(37), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(39), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [104] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(20), 1,
      sym_quantifier,
    STATE(27), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(41), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [129] = 7,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym__field_name,
    STATE(5), 8,
      sym__definition,
      sym_field_definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_named_node_repeat1,
  [158] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(18), 1,
      sym_quantifier,
    STATE(21), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(45), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [183] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(19), 1,
      sym_quantifier,
    STATE(30), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [208] = 5,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(35), 1,
      sym_quantifier,
    STATE(36), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(19), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [233] = 5,
    ACTIONS(53), 1,
      aux_sym_string_token1,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    STATE(12), 7,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [257] = 6,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    STATE(17), 7,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [282] = 5,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_RBRACK,
    STATE(16), 7,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [304] = 5,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(12), 7,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [326] = 5,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
    STATE(12), 7,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [348] = 5,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(12), 7,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
      aux_sym_program_repeat1,
  [370] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(32), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(74), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [387] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(39), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [404] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(38), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [421] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(17), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [438] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [455] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [472] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(84), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [489] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [506] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(22), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [523] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [540] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [557] = 3,
    ACTIONS(96), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [574] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(41), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [591] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(25), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [608] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(101), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [625] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(24), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [642] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(105), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [659] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(23), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [676] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(39), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [693] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(109), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [710] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [727] = 3,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(29), 2,
      sym_capture,
      aux_sym_list_repeat1,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [744] = 4,
    ACTIONS(5), 1,
      aux_sym_string_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    STATE(47), 6,
      sym__definition,
      sym_list,
      sym_grouping,
      sym_anonymous_node,
      sym_named_node,
      sym_predicate,
  [762] = 1,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_AT,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [773] = 1,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_AT,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [784] = 1,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [794] = 4,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_string_token1,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(46), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [809] = 4,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_string_token1,
    STATE(51), 1,
      sym_parameters,
    STATE(44), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [824] = 4,
    ACTIONS(125), 1,
      anon_sym_AT,
    ACTIONS(128), 1,
      aux_sym_string_token1,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(46), 3,
      sym_capture,
      sym_string,
      aux_sym_parameters_repeat1,
  [839] = 1,
    ACTIONS(133), 5,
      sym_identifier,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [847] = 1,
    ACTIONS(135), 3,
      aux_sym_string_token1,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [853] = 1,
    ACTIONS(137), 3,
      anon_sym_AT,
      aux_sym_string_token1,
      anon_sym_RPAREN,
  [859] = 1,
    ACTIONS(139), 2,
      anon_sym_AT,
      aux_sym_string_token1,
  [864] = 1,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
  [868] = 1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
  [872] = 1,
    ACTIONS(145), 1,
      anon_sym_COLON,
  [876] = 1,
    ACTIONS(147), 1,
      sym_capture_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 25,
  [SMALL_STATE(5)] = 50,
  [SMALL_STATE(6)] = 79,
  [SMALL_STATE(7)] = 104,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 158,
  [SMALL_STATE(10)] = 183,
  [SMALL_STATE(11)] = 208,
  [SMALL_STATE(12)] = 233,
  [SMALL_STATE(13)] = 257,
  [SMALL_STATE(14)] = 282,
  [SMALL_STATE(15)] = 304,
  [SMALL_STATE(16)] = 326,
  [SMALL_STATE(17)] = 348,
  [SMALL_STATE(18)] = 370,
  [SMALL_STATE(19)] = 387,
  [SMALL_STATE(20)] = 404,
  [SMALL_STATE(21)] = 421,
  [SMALL_STATE(22)] = 438,
  [SMALL_STATE(23)] = 455,
  [SMALL_STATE(24)] = 472,
  [SMALL_STATE(25)] = 489,
  [SMALL_STATE(26)] = 506,
  [SMALL_STATE(27)] = 523,
  [SMALL_STATE(28)] = 540,
  [SMALL_STATE(29)] = 557,
  [SMALL_STATE(30)] = 574,
  [SMALL_STATE(31)] = 591,
  [SMALL_STATE(32)] = 608,
  [SMALL_STATE(33)] = 625,
  [SMALL_STATE(34)] = 642,
  [SMALL_STATE(35)] = 659,
  [SMALL_STATE(36)] = 676,
  [SMALL_STATE(37)] = 693,
  [SMALL_STATE(38)] = 710,
  [SMALL_STATE(39)] = 727,
  [SMALL_STATE(40)] = 744,
  [SMALL_STATE(41)] = 762,
  [SMALL_STATE(42)] = 773,
  [SMALL_STATE(43)] = 784,
  [SMALL_STATE(44)] = 794,
  [SMALL_STATE(45)] = 809,
  [SMALL_STATE(46)] = 824,
  [SMALL_STATE(47)] = 839,
  [SMALL_STATE(48)] = 847,
  [SMALL_STATE(49)] = 853,
  [SMALL_STATE(50)] = 859,
  [SMALL_STATE(51)] = 864,
  [SMALL_STATE(52)] = 868,
  [SMALL_STATE(53)] = 872,
  [SMALL_STATE(54)] = 876,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 1),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(53),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(14),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2), SHIFT_REPEAT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_named_node_repeat1, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 4, .production_id = 2),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 3, .production_id = 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(4),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(14),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(13),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3, .production_id = 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4, .production_id = 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 6, .production_id = 8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, .production_id = 4),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 3, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 8),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(54),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_node, 2, .production_id = 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 4, .production_id = 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_node, 5, .production_id = 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 5, .production_id = 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 4, .production_id = 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 2, .production_id = 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantifier, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 5, .production_id = 7),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(54),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(49),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 2, .production_id = 6),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_name, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_type, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_scheme(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
